import{a as d}from"./assets/vendor-bdb8a163.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();d.defaults.headers.common["x-api-key"]="live_4cE17S90WSsTbHmoTpSGVg6M02m3QTLjOZomeFIBAhuSv4CrP0UGBHOvFaZpMJkP";const y=async()=>{try{return(await d.get("https://api.thecatapi.com/v1/breeds")).data}catch{throw new Error("Failed to fetch breeds")}},f=async s=>{try{return(await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${s}`)).data[0]}catch{throw new Error("Failed to fetch cat information")}};document.addEventListener("DOMContentLoaded",async()=>{const s=document.getElementById("breed-select"),n=document.getElementById("loader"),i=document.getElementById("error"),a=document.getElementById("cat-info"),e=()=>n.style.display="block",t=()=>n.style.display="none",c=o=>{i.textContent=o,i.style.display="block"},l=()=>i.style.display="none",p=async()=>{try{e(),l();const o=await y();s.innerHTML=o.map(r=>`<option value="${r.id}">${r.name}</option>`).join(""),new SlimSelect({select:"#breed-select"})}catch(o){c(o.message)}finally{t(),s.style.display="none"}},m=async o=>{try{e(),l(),a.style.display="none";const r=await f(o);a.innerHTML=`
        <div class="cat-image">
          <img src="${r.url}" alt="${r.breeds[0].name}">
        </div>
        <div class="cat-details">
          <h2>${r.breeds[0].name}</h2>
          <p>${r.breeds[0].description}</p>
          <p><strong>Temperament:</strong> ${r.breeds[0].temperament}</p>
        </div>
`,a.style.display="flex"}catch(r){c(r.message)}finally{t()}};s.addEventListener("change",o=>{const r=o.target.value;r&&m(r)}),await p()});
//# sourceMappingURL=commonHelpers.js.map
