import{a as d}from"./assets/vendor-bdb8a163.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();d.defaults.headers.common["x-api-key"]="live_4cE17S90WSsTbHmoTpSGVg6M02m3QTLjOZomeFIBAhuSv4CrP0UGBHOvFaZpMJkP";const y=async()=>{try{return(await d.get("https://api.thecatapi.com/v1/breeds")).data}catch{throw new Error("Failed to fetch breeds")}},f=async o=>{try{return(await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${o}`)).data[0]}catch{throw new Error("Failed to fetch cat information")}};document.addEventListener("DOMContentLoaded",async()=>{const o=document.getElementById("breed-select"),n=document.getElementById("loader"),i=document.getElementById("error"),c=document.getElementById("cat-info"),e=()=>n.style.display="block",r=()=>n.style.display="none",a=s=>{i.textContent=s,i.style.display="block"},l=()=>i.style.display="none",p=async()=>{try{e(),l();const s=await y();o.innerHTML=s.map(t=>`<option value="${t.id}">${t.name}</option>`).join(""),new SlimSelect({select:"#breed-select"}),o.style.display="block"}catch(s){a(s.message)}finally{r(),o.style.display="none"}},m=async s=>{try{e(),l(),c.style.display="none";const t=await f(s);if(!t||t.length===0){a("There is no information about this cat");return}c.innerHTML=`
        <div class="cat-image">
          <img src="${t.url}" alt="${t.breeds[0].name}">
        </div>
        <div class="cat-details">
          <h2>${t.breeds[0].name}</h2>
          <p>${t.breeds[0].description}</p>
          <p><strong>Temperament:</strong> ${t.breeds[0].temperament}</p>
        </div>
`,c.style.display="flex"}catch(t){a(t.message)}finally{r()}};o.addEventListener("change",s=>{const t=s.target.value;t&&m(t)}),await p()});
//# sourceMappingURL=commonHelpers.js.map
